apiVersion: v1
kind: ConfigMap
metadata:
  name: reeve-be-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  RDS_ENDPOINT: {{ .Values.config.rdsEndpoint | quote }}
  S3_BUCKET_NAME: {{ .Values.config.s3BucketName | quote }}
  JWT_ACCESS_EXPIRATION: {{ .Values.config.jwtAccessExpiration | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.config.jwtRefreshExpiration | quote }}
