apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reeve-be-external-secret
spec:
  secretStoreRef:
    name: reeve-be-parameterstore
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.dbPasswordKey }}
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.jwtSecretKey }}
