apiVersion: v1
kind: Service
metadata:
  name: reeve-be-service
spec:
  type: ClusterIP
  selector:
    app: community
    tier: backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
